### ISSUE TITLE
Add possibility to disable all Cops

### ISSUE THREAD

**Issue by stefan-kolb** [stefan-kolb/texcop#10]
e.g., for configuration files 

```
AllCops:
  Exclude:
  - "file"
```

Also inline?!

Also exclude files from top-level cop like:
```
Style:
  Exclude:
  - "file"
```
instead of

```
Style/AllCops:
  Exclude:
  - "file"
```

or 

```
Style/SomeCop:
  Exclude:
  - "file"

Style/SomeOtherCop:
  Exclude:
  - "file"
```
